// <auto-generated />
namespace Warehouse_Manage_WPF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ChangedRelationshipBetweenDevicesAndProjectsToOneToMany : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangedRelationshipBetweenDevicesAndProjectsToOneToMany));
        
        string IMigrationMetadata.Id
        {
            get { return "202004231412439_ChangedRelationshipBetweenDevicesAndProjectsToOneToMany"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
